# Generated by Django 6.0.4 on 2026-09-07 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowed', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='borrowedbook',
            constraint=models.UniqueConstraint(condition=models.Q(('return_date__isnull', True)), fields=('user', 'book'), name='one_active_borrowing_per_user_book'),
        ),
    ]
