# Generated by Django 6.0.4 on 2026-09-08 14:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_comment_rating'),
        ('borrowed', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='borrowedbook',
            constraint=models.CheckConstraint(condition=models.Q(('return_date__isnull', True), ('return_date__gte', models.F('borrowed_date')), _connector='OR'), name='chk_return_after_borrow'),
        ),
    ]
