# Generated by Django 6.0.4 on 2026-09-08 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_comment_rating'),
        ('borrowed', '0003_borrowedbook_chk_return_after_borrow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='borrowedbook',
            name='chk_return_after_borrow',
        ),
        migrations.RenameField(
            model_name='borrowedbook',
            old_name='borrowed_date',
            new_name='borrow_date',
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowed_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='borrowedbook',
            constraint=models.CheckConstraint(condition=models.Q(('return_date__isnull', True), ('return_date__gte', models.F('borrow_date')), _connector='OR'), name='chk_return_after_borrow'),
        ),
    ]
