# Generated by Django 6.0.4 on 2026-09-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowed', '0004_remove_borrowedbook_chk_return_after_borrow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='due_date',
            field=models.DateField(default='2026-9-23'),
            preserve_default=False,
        ),
    ]
