# Generated by Django 6.0.4 on 2026-09-27 12:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowed', '0005_borrowedbook_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='borrow_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
