# Generated by Django 6.0.4 on 2026-05-13 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All', '0002_alter_book_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='book',
            name='availableCopies',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='book_covers/default.jpg', null=True, upload_to='book_covers/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='totalCopies',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='borrowedbooks',
            name='bookId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to='All.book'),
        ),
        migrations.AlterField(
            model_name='borrowedbooks',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='bookId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='All.book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='All.category'),
        ),
    ]
