# Generated by Django 6.0.5 on 2026-05-13 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('All', '0003_category_book_created_at_alter_book_availablecopies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
    ]
