# Generated by Django 6.0.4 on 2026-09-08 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='books',
        ),
    ]
